version: '3.1'
services:
  sportybe-persistence.postgre:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=shopping_list
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - 15000:5432
  redis:
    image: "redis:alpine"
    environment:
      - REDIS_PASSWORD=root
    ports:
      - 6379:6379
